server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/literature_content?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.literature.content.entity
