server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
#   config: classpath:logback-spring.xml
  file:
    path: ${log.home:${user.home}/logs/seata}

console:
  user:
    username: seata
    password: seata

seata:
  config:
    type: file
    nacos:
      server-addr: nacos:8848
      namespace: ""
      group: SEATA_GROUP
      data-id: seataServer.properties
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: nacos:8848
      namespace: ""
      group: SEATA_GROUP
      cluster: default
      username: nacos
      password: nacos
  store:
    mode: file
    db:
      datasource: druid
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql:3306/seata?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8
      user: root
      password: root
      min-conn: 10
      max-conn: 100
      global-table: global_table
      branch-table: branch_table
      lock-table: lock_table
      distributed-lock-table: distributed_lock
      query-limit: 1000
      max-wait: 5000
  security:
    secretKey: SeataSecretKey0123456789876543210
    tokenValidityInMilliseconds: 1800000
