server:
  port: 18089

spring:
  application:
    name: monitor-service
  config:
    import: "optional:nacos:monitor-service.yml"
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        file-extension: yaml
        shared-configs:
          - data-id: literature-common.yaml
            refresh: true
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
