server:
  port: 18087

spring:
  application:
    name: search-service
  config:
    import: "optional:nacos:search-service.yml"
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        file-extension: yaml
        shared-configs:
          - data-id: literature-common.yaml
            refresh: true
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
