// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chat-service/src/main/proto/ChatProtocol.proto
// Protobuf Java Version: 4.29.3

package com.literature.chat.netty.protocol;

public interface ChatPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.literature.chat.netty.protocol.ChatPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.literature.chat.netty.protocol.CmdType cmd = 1;</code>
   * @return The enum numeric value on the wire for cmd.
   */
  int getCmdValue();
  /**
   * <code>.com.literature.chat.netty.protocol.CmdType cmd = 1;</code>
   * @return The cmd.
   */
  com.literature.chat.netty.protocol.CmdType getCmd();

  /**
   * <pre>
   * 会话ID (单聊/群聊)
   * </pre>
   *
   * <code>int64 session_id = 2;</code>
   * @return The sessionId.
   */
  long getSessionId();

  /**
   * <pre>
   * 发送者ID
   * </pre>
   *
   * <code>int64 sender_id = 3;</code>
   * @return The senderId.
   */
  long getSenderId();

  /**
   * <pre>
   * 接收者ID (用户或群组ID)
   * </pre>
   *
   * <code>int64 target_id = 4;</code>
   * @return The targetId.
   */
  long getTargetId();

  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 内容类型 (text, image, file)
   * </pre>
   *
   * <code>string content_type = 6;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <pre>
   * 内容类型 (text, image, file)
   * </pre>
   *
   * <code>string content_type = 6;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 扩展字段 (JSON)
   * </pre>
   *
   * <code>string extra = 8;</code>
   * @return The extra.
   */
  java.lang.String getExtra();
  /**
   * <pre>
   * 扩展字段 (JSON)
   * </pre>
   *
   * <code>string extra = 8;</code>
   * @return The bytes for extra.
   */
  com.google.protobuf.ByteString
      getExtraBytes();

  /**
   * <pre>
   * 是否加密
   * </pre>
   *
   * <code>bool encrypted = 9;</code>
   * @return The encrypted.
   */
  boolean getEncrypted();

  /**
   * <pre>
   * 加密后的内容
   * </pre>
   *
   * <code>bytes enc_content = 10;</code>
   * @return The encContent.
   */
  com.google.protobuf.ByteString getEncContent();
}

