// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chat-service/src/main/proto/ChatProtocol.proto
// Protobuf Java Version: 4.29.3

package com.literature.chat.netty.protocol;

/**
 * <pre>
 * 基础消息负载
 * </pre>
 *
 * Protobuf type {@code com.literature.chat.netty.protocol.ChatPayload}
 */
public final class ChatPayload extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.literature.chat.netty.protocol.ChatPayload)
    ChatPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ChatPayload.class.getName());
  }
  // Use ChatPayload.newBuilder() to construct.
  private ChatPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ChatPayload() {
    cmd_ = 0;
    content_ = "";
    contentType_ = "";
    extra_ = "";
    encContent_ = com.google.protobuf.ByteString.EMPTY;
  }


  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.literature.chat.netty.protocol.ChatProtocol.internal_static_com_literature_chat_netty_protocol_ChatPayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.literature.chat.netty.protocol.ChatProtocol.internal_static_com_literature_chat_netty_protocol_ChatPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.literature.chat.netty.protocol.ChatPayload.class, com.literature.chat.netty.protocol.ChatPayload.Builder.class);
  }

  public static final int CMD_FIELD_NUMBER = 1;
  private int cmd_ = 0;
  /**
   * <code>.com.literature.chat.netty.protocol.CmdType cmd = 1;</code>
   * @return The enum numeric value on the wire for cmd.
   */
  @java.lang.Override public int getCmdValue() {
    return cmd_;
  }
  /**
   * <code>.com.literature.chat.netty.protocol.CmdType cmd = 1;</code>
   * @return The cmd.
   */
  @java.lang.Override public com.literature.chat.netty.protocol.CmdType getCmd() {
    com.literature.chat.netty.protocol.CmdType result = com.literature.chat.netty.protocol.CmdType.forNumber(cmd_);
    return result == null ? com.literature.chat.netty.protocol.CmdType.UNRECOGNIZED : result;
  }

  public static final int SESSION_ID_FIELD_NUMBER = 2;
  private long sessionId_ = 0L;
  /**
   * <pre>
   * 会话ID (单聊/群聊)
   * </pre>
   *
   * <code>int64 session_id = 2;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public long getSessionId() {
    return sessionId_;
  }

  public static final int SENDER_ID_FIELD_NUMBER = 3;
  private long senderId_ = 0L;
  /**
   * <pre>
   * 发送者ID
   * </pre>
   *
   * <code>int64 sender_id = 3;</code>
   * @return The senderId.
   */
  @java.lang.Override
  public long getSenderId() {
    return senderId_;
  }

  public static final int TARGET_ID_FIELD_NUMBER = 4;
  private long targetId_ = 0L;
  /**
   * <pre>
   * 接收者ID (用户或群组ID)
   * </pre>
   *
   * <code>int64 target_id = 4;</code>
   * @return The targetId.
   */
  @java.lang.Override
  public long getTargetId() {
    return targetId_;
  }

  public static final int CONTENT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object content_ = "";
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 5;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_TYPE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contentType_ = "";
  /**
   * <pre>
   * 内容类型 (text, image, file)
   * </pre>
   *
   * <code>string content_type = 6;</code>
   * @return The contentType.
   */
  @java.lang.Override
  public java.lang.String getContentType() {
    java.lang.Object ref = contentType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contentType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 内容类型 (text, image, file)
   * </pre>
   *
   * <code>string content_type = 6;</code>
   * @return The bytes for contentType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentTypeBytes() {
    java.lang.Object ref = contentType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contentType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int EXTRA_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object extra_ = "";
  /**
   * <pre>
   * 扩展字段 (JSON)
   * </pre>
   *
   * <code>string extra = 8;</code>
   * @return The extra.
   */
  @java.lang.Override
  public java.lang.String getExtra() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extra_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 扩展字段 (JSON)
   * </pre>
   *
   * <code>string extra = 8;</code>
   * @return The bytes for extra.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExtraBytes() {
    java.lang.Object ref = extra_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENCRYPTED_FIELD_NUMBER = 9;
  private boolean encrypted_ = false;
  /**
   * <pre>
   * 是否加密
   * </pre>
   *
   * <code>bool encrypted = 9;</code>
   * @return The encrypted.
   */
  @java.lang.Override
  public boolean getEncrypted() {
    return encrypted_;
  }

  public static final int ENC_CONTENT_FIELD_NUMBER = 10;
  private com.google.protobuf.ByteString encContent_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * 加密后的内容
   * </pre>
   *
   * <code>bytes enc_content = 10;</code>
   * @return The encContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncContent() {
    return encContent_;
  }


  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cmd_ != com.literature.chat.netty.protocol.CmdType.UNKNOWN.getNumber()) {
      output.writeEnum(1, cmd_);
    }
    if (sessionId_ != 0L) {
      output.writeInt64(2, sessionId_);
    }
    if (senderId_ != 0L) {
      output.writeInt64(3, senderId_);
    }
    if (targetId_ != 0L) {
      output.writeInt64(4, targetId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, content_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contentType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, contentType_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(extra_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, extra_);
    }
    if (encrypted_ != false) {
      output.writeBool(9, encrypted_);
    }
    if (!encContent_.isEmpty()) {
      output.writeBytes(10, encContent_);
    }
    getUnknownFields().writeTo(output);

  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cmd_ != com.literature.chat.netty.protocol.CmdType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, cmd_);
    }
    if (sessionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, sessionId_);
    }
    if (senderId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, senderId_);
    }
    if (targetId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, targetId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, content_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contentType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, contentType_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(extra_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, extra_);
    }
    if (encrypted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, encrypted_);
    }
    if (!encContent_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(10, encContent_);
    }
    size += getUnknownFields().getSerializedSize();

    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.literature.chat.netty.protocol.ChatPayload)) {
      return super.equals(obj);
    }
    com.literature.chat.netty.protocol.ChatPayload other = (com.literature.chat.netty.protocol.ChatPayload) obj;

    if (cmd_ != other.cmd_) return false;
    if (getSessionId()
        != other.getSessionId()) return false;
    if (getSenderId()
        != other.getSenderId()) return false;
    if (getTargetId()
        != other.getTargetId()) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getContentType()
        .equals(other.getContentType())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getExtra()
        .equals(other.getExtra())) return false;
    if (getEncrypted()
        != other.getEncrypted()) return false;
    if (!getEncContent()
        .equals(other.getEncContent())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;

  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CMD_FIELD_NUMBER;
    hash = (53 * hash) + cmd_;
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSessionId());
    hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSenderId());
    hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTargetId());
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + CONTENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getContentType().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getExtra().hashCode();
    hash = (37 * hash) + ENCRYPTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEncrypted());
    hash = (37 * hash) + ENC_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getEncContent().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;

  }

  public static com.literature.chat.netty.protocol.ChatPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.literature.chat.netty.protocol.ChatPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.literature.chat.netty.protocol.ChatPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.literature.chat.netty.protocol.ChatPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.literature.chat.netty.protocol.ChatPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.literature.chat.netty.protocol.ChatPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.literature.chat.netty.protocol.ChatPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.literature.chat.netty.protocol.ChatPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.literature.chat.netty.protocol.ChatPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.literature.chat.netty.protocol.ChatPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.literature.chat.netty.protocol.ChatPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.literature.chat.netty.protocol.ChatPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.literature.chat.netty.protocol.ChatPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 基础消息负载
   * </pre>
   *
   * Protobuf type {@code com.literature.chat.netty.protocol.ChatPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.literature.chat.netty.protocol.ChatPayload)
      com.literature.chat.netty.protocol.ChatPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.literature.chat.netty.protocol.ChatProtocol.internal_static_com_literature_chat_netty_protocol_ChatPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.literature.chat.netty.protocol.ChatProtocol.internal_static_com_literature_chat_netty_protocol_ChatPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.literature.chat.netty.protocol.ChatPayload.class, com.literature.chat.netty.protocol.ChatPayload.Builder.class);
    }

    // Construct using com.literature.chat.netty.protocol.ChatPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cmd_ = 0;
      sessionId_ = 0L;
      senderId_ = 0L;
      targetId_ = 0L;
      content_ = "";
      contentType_ = "";
      timestamp_ = 0L;
      extra_ = "";
      encrypted_ = false;
      encContent_ = com.google.protobuf.ByteString.EMPTY;
      return this;

    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.literature.chat.netty.protocol.ChatProtocol.internal_static_com_literature_chat_netty_protocol_ChatPayload_descriptor;
    }

    @java.lang.Override
    public com.literature.chat.netty.protocol.ChatPayload getDefaultInstanceForType() {
      return com.literature.chat.netty.protocol.ChatPayload.getDefaultInstance();
    }

    @java.lang.Override
    public com.literature.chat.netty.protocol.ChatPayload build() {
      com.literature.chat.netty.protocol.ChatPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.literature.chat.netty.protocol.ChatPayload buildPartial() {
      com.literature.chat.netty.protocol.ChatPayload result = new com.literature.chat.netty.protocol.ChatPayload(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.literature.chat.netty.protocol.ChatPayload result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cmd_ = cmd_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.senderId_ = senderId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.targetId_ = targetId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.content_ = content_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.contentType_ = contentType_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.extra_ = extra_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.encrypted_ = encrypted_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.encContent_ = encContent_;
      }
    }


    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.literature.chat.netty.protocol.ChatPayload) {
        return mergeFrom((com.literature.chat.netty.protocol.ChatPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.literature.chat.netty.protocol.ChatPayload other) {
      if (other == com.literature.chat.netty.protocol.ChatPayload.getDefaultInstance()) return this;
      if (other.cmd_ != 0) {
        setCmdValue(other.getCmdValue());
      }
      if (other.getSessionId() != 0L) {
        setSessionId(other.getSessionId());
      }
      if (other.getSenderId() != 0L) {
        setSenderId(other.getSenderId());
      }
      if (other.getTargetId() != 0L) {
        setTargetId(other.getTargetId());
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getContentType().isEmpty()) {
        contentType_ = other.contentType_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getExtra().isEmpty()) {
        extra_ = other.extra_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getEncrypted() != false) {
        setEncrypted(other.getEncrypted());
      }
      if (other.getEncContent() != com.google.protobuf.ByteString.EMPTY) {
        setEncContent(other.getEncContent());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;

    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              cmd_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              sessionId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              senderId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              targetId_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              contentType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              extra_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              encrypted_ = input.readBool();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              encContent_ = input.readBytes();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)

      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int cmd_ = 0;
    /**
     * <code>.com.literature.chat.netty.protocol.CmdType cmd = 1;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    @java.lang.Override public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>.com.literature.chat.netty.protocol.CmdType cmd = 1;</code>
     * @param value The enum numeric value on the wire for cmd to set.
     * @return This builder for chaining.
     */
    public Builder setCmdValue(int value) {
      cmd_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.literature.chat.netty.protocol.CmdType cmd = 1;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public com.literature.chat.netty.protocol.CmdType getCmd() {
      com.literature.chat.netty.protocol.CmdType result = com.literature.chat.netty.protocol.CmdType.forNumber(cmd_);
      return result == null ? com.literature.chat.netty.protocol.CmdType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.literature.chat.netty.protocol.CmdType cmd = 1;</code>
     * @param value The cmd to set.
     * @return This builder for chaining.
     */
    public Builder setCmd(com.literature.chat.netty.protocol.CmdType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      cmd_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.literature.chat.netty.protocol.CmdType cmd = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCmd() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cmd_ = 0;
      onChanged();
      return this;
    }

    private long sessionId_ ;
    /**
     * <pre>
     * 会话ID (单聊/群聊)
     * </pre>
     *
     * <code>int64 session_id = 2;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public long getSessionId() {
      return sessionId_;
    }
    /**
     * <pre>
     * 会话ID (单聊/群聊)
     * </pre>
     *
     * <code>int64 session_id = 2;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(long value) {

      sessionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话ID (单聊/群聊)
     * </pre>
     *
     * <code>int64 session_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sessionId_ = 0L;
      onChanged();
      return this;
    }

    private long senderId_ ;
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 sender_id = 3;</code>
     * @return The senderId.
     */
    @java.lang.Override
    public long getSenderId() {
      return senderId_;
    }
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 sender_id = 3;</code>
     * @param value The senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderId(long value) {

      senderId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>int64 sender_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      senderId_ = 0L;
      onChanged();
      return this;
    }

    private long targetId_ ;
    /**
     * <pre>
     * 接收者ID (用户或群组ID)
     * </pre>
     *
     * <code>int64 target_id = 4;</code>
     * @return The targetId.
     */
    @java.lang.Override
    public long getTargetId() {
      return targetId_;
    }
    /**
     * <pre>
     * 接收者ID (用户或群组ID)
     * </pre>
     *
     * <code>int64 target_id = 4;</code>
     * @param value The targetId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetId(long value) {

      targetId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收者ID (用户或群组ID)
     * </pre>
     *
     * <code>int64 target_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      targetId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 5;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object contentType_ = "";
    /**
     * <pre>
     * 内容类型 (text, image, file)
     * </pre>
     *
     * <code>string content_type = 6;</code>
     * @return The contentType.
     */
    public java.lang.String getContentType() {
      java.lang.Object ref = contentType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 内容类型 (text, image, file)
     * </pre>
     *
     * <code>string content_type = 6;</code>
     * @return The bytes for contentType.
     */
    public com.google.protobuf.ByteString
        getContentTypeBytes() {
      java.lang.Object ref = contentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 内容类型 (text, image, file)
     * </pre>
     *
     * <code>string content_type = 6;</code>
     * @param value The contentType to set.
     * @return This builder for chaining.
     */
    public Builder setContentType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contentType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 内容类型 (text, image, file)
     * </pre>
     *
     * <code>string content_type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentType() {
      contentType_ = getDefaultInstance().getContentType();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 内容类型 (text, image, file)
     * </pre>
     *
     * <code>string content_type = 6;</code>
     * @param value The bytes for contentType to set.
     * @return This builder for chaining.
     */
    public Builder setContentTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contentType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object extra_ = "";
    /**
     * <pre>
     * 扩展字段 (JSON)
     * </pre>
     *
     * <code>string extra = 8;</code>
     * @return The extra.
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 扩展字段 (JSON)
     * </pre>
     *
     * <code>string extra = 8;</code>
     * @return The bytes for extra.
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 扩展字段 (JSON)
     * </pre>
     *
     * <code>string extra = 8;</code>
     * @param value The extra to set.
     * @return This builder for chaining.
     */
    public Builder setExtra(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      extra_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展字段 (JSON)
     * </pre>
     *
     * <code>string extra = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtra() {
      extra_ = getDefaultInstance().getExtra();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展字段 (JSON)
     * </pre>
     *
     * <code>string extra = 8;</code>
     * @param value The bytes for extra to set.
     * @return This builder for chaining.
     */
    public Builder setExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      extra_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private boolean encrypted_;
    /**
     * <pre>
     * 是否加密
     * </pre>
     *
     * <code>bool encrypted = 9;</code>
     * @return The encrypted.
     */
    public boolean getEncrypted() {
      return encrypted_;
    }
    /**
     * <pre>
     * 是否加密
     * </pre>
     *
     * <code>bool encrypted = 9;</code>
     * @param value The encrypted to set.
     * @return This builder for chaining.
     */
    public Builder setEncrypted(boolean value) {
      encrypted_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否加密
     * </pre>
     *
     * <code>bool encrypted = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncrypted() {
      bitField0_ = (bitField0_ & ~0x00000100);
      encrypted_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString encContent_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 加密后的内容
     * </pre>
     *
     * <code>bytes enc_content = 10;</code>
     * @return The encContent.
     */
    public com.google.protobuf.ByteString getEncContent() {
      return encContent_;
    }
    /**
     * <pre>
     * 加密后的内容
     * </pre>
     *
     * <code>bytes enc_content = 10;</code>
     * @param value The encContent to set.
     * @return This builder for chaining.
     */
    public Builder setEncContent(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      encContent_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 加密后的内容
     * </pre>
     *
     * <code>bytes enc_content = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncContent() {
      bitField0_ = (bitField0_ & ~0x00000200);
      encContent_ = com.google.protobuf.ByteString.EMPTY;
      onChanged();
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.literature.chat.netty.protocol.ChatPayload)
  }

  // @@protoc_insertion_point(class_scope:com.literature.chat.netty.protocol.ChatPayload)
  private static final com.literature.chat.netty.protocol.ChatPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.literature.chat.netty.protocol.ChatPayload();
  }

  public static com.literature.chat.netty.protocol.ChatPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatPayload>
      PARSER = new com.google.protobuf.AbstractParser<ChatPayload>() {
    @java.lang.Override
    public ChatPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.literature.chat.netty.protocol.ChatPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

