// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chat-service/src/main/proto/ChatProtocol.proto
// Protobuf Java Version: 4.29.3

package com.literature.chat.netty.protocol;

/**
 * <pre>
 * 消息类型
 * </pre>
 *
 * Protobuf enum {@code com.literature.chat.netty.protocol.CmdType}
 */
public enum CmdType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <pre>
   * 心跳
   * </pre>
   *
   * <code>HEARTBEAT = 1;</code>
   */
  HEARTBEAT(1),
  /**
   * <pre>
   * 认证
   * </pre>
   *
   * <code>AUTH = 2;</code>
   */
  AUTH(2),
  /**
   * <pre>
   * 单聊消息
   * </pre>
   *
   * <code>SINGLE_CHAT = 3;</code>
   */
  SINGLE_CHAT(3),
  /**
   * <pre>
   * 群聊消息
   * </pre>
   *
   * <code>GROUP_CHAT = 4;</code>
   */
  GROUP_CHAT(4),
  /**
   * <pre>
   * 消息回执
   * </pre>
   *
   * <code>ACK = 5;</code>
   */
  ACK(5),
  /**
   * <pre>
   * 错误响应
   * </pre>
   *
   * <code>ERROR = 6;</code>
   */
  ERROR(6),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      CmdType.class.getName());
  }
  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <pre>
   * 心跳
   * </pre>
   *
   * <code>HEARTBEAT = 1;</code>
   */
  public static final int HEARTBEAT_VALUE = 1;
  /**
   * <pre>
   * 认证
   * </pre>
   *
   * <code>AUTH = 2;</code>
   */
  public static final int AUTH_VALUE = 2;
  /**
   * <pre>
   * 单聊消息
   * </pre>
   *
   * <code>SINGLE_CHAT = 3;</code>
   */
  public static final int SINGLE_CHAT_VALUE = 3;
  /**
   * <pre>
   * 群聊消息
   * </pre>
   *
   * <code>GROUP_CHAT = 4;</code>
   */
  public static final int GROUP_CHAT_VALUE = 4;
  /**
   * <pre>
   * 消息回执
   * </pre>
   *
   * <code>ACK = 5;</code>
   */
  public static final int ACK_VALUE = 5;
  /**
   * <pre>
   * 错误响应
   * </pre>
   *
   * <code>ERROR = 6;</code>
   */
  public static final int ERROR_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CmdType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CmdType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return HEARTBEAT;
      case 2: return AUTH;
      case 3: return SINGLE_CHAT;
      case 4: return GROUP_CHAT;
      case 5: return ACK;
      case 6: return ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CmdType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CmdType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CmdType>() {
          public CmdType findValueByNumber(int number) {
            return CmdType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.literature.chat.netty.protocol.ChatProtocol.getDescriptor().getEnumTypes().get(0);
  }

  private static final CmdType[] VALUES = values();

  public static CmdType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CmdType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.literature.chat.netty.protocol.CmdType)
}

